### ISSUE TITLE
可知密匙无法安装

### ISSUE THREAD

**Issue by willzoe** [zzyandzzy/xp_keledge#1]
手机型号：华为荣耀畅玩5A
EMUI系统：4.1.3
android版本：6.0

请问如何解决呢？

**Comment by zzyandzzy** [comment]
有安装Xposed吗，有的话我重新编译一下，新版本可知下载，不用那么麻烦了

**Comment by willzoe** [comment]
有`Xposed`，安装密匙的时候提示`该安装包未包含任何证书`

**Comment by zzyandzzy** [comment]
我重新编译了另外一个更方便的[可知下载](https://github.com/zzyandzzy/xp_keledge/releases)，你可以去下载试试

**Comment by willzoe** [comment]
谢谢～

但是还会遇到相同的问题：


![Screenshot](https://user-images.githubusercontent.com/14708901/75094215-3509b100-55c4-11ea-940f-ecbd92d47dff.png)


第一次用华为手机，我再找找解决办法。

**Comment by zzyandzzy** [comment]
我按照百度上的说重新编译了下，你去试试，[可知下载0.2](https://github.com/zzyandzzy/xp_keledge/releases/download/0.2/release-0.2.apk)

**Comment by willzoe** [comment]
安装成功～

**Comment by filesdrive** [comment]
您好，编译的apk无法安装，提示解析包时出现问题。
手机型号：红米1S
MUI系统：MIUI 9.2.2.0
android版本：4.4.2
能否看一下

**Comment by zzyandzzy** [comment]
> 您好，编译的apk无法安装，提示解析包时出现问题。
> 手机型号：红米1S
> MUI系统：MIUI 9.2.2.0
> android版本：4.4.2
> 能否看一下

我限制了最小版本为安卓5.0，你自己改下[build.gradle](https://github.com/zzyandzzy/xp_keledge/blob/master/app/build.gradle)里面的minSdkVersion
