### ISSUE TITLE
发生异常错误

### ISSUE THREAD

**Issue by willzoe** [zzyandzzy/xp_keledge#2]
点击pdf书籍后，提示`发生异常错误，请稍候再试！`
可知版本：2.3.2
![Screenshot1](https://user-images.githubusercontent.com/14708901/75094667-713f1080-55c8-11ea-995f-300f83457285.png)

**Comment by zzyandzzy** [comment]
是安装了可知下载后才提示的还是怎么?手动给可知下载APP存储权限了吗?

**Comment by willzoe** [comment]
安装`可知下载`之后才安装`可知`

已手动赋予`可知下载`存储权限
![Screenshot2](https://user-images.githubusercontent.com/14708901/75094915-874dd080-55ca-11ea-833d-8a908b4af4ec.png)

**Comment by zzyandzzy** [comment]
其他书籍呢?可以切换到移动网络试试，如果都不行的话有两个解决方案，一个是先卸载可知下载（如果激活了Xposed模块还要重启一下），再试试能不能打开可知在线阅读，如果可以安装可知下载，激活Xposed模块，手机USB链接电脑，输入
```
adb logcat | grep "Xposed"
```
并贴上log

第二个解决方案就是留下你邮箱和你要下载的书籍，我给你下载好了后发过去。

**Comment by willzoe** [comment]
可能是`可知`有些问题。卸载`可知下载`并且重启之后，epub格式的书籍可以正常阅读，pdf格式的无法阅读。

您的`可知`版本也是`2.3.2`吗？

我的邮箱是`zw1710012427@gmail.com`，需要的书籍是`视觉SLAM十四讲 从理论到实践 第2版`。

谢谢您～

**Comment by zzyandzzy** [comment]
我的可知版本是2.3.2，我之前也遇到过这个问题，是可知服务器不稳定出现的问题。

**Comment by zzyandzzy** [comment]
已发送

**Comment by sdieedu** [comment]
多版本可知app，测试了一下：点击pdf书籍后，提示### **发生异常错误，请稍候再试！2秒后退出阅读**
问题是：网页阅读无障碍啊
咋办？

**Comment by willzoe** [comment]
可知还是无法正常阅读。尝试了一下第一种方法，下面是log信息：
```
$ adb logcat | grep "Xposed"
02-26 13:12:50.340  7693  7901 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/main/libsgmain_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@main@libsgmain_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:12:51.545  7693  7693 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:12:51.642  7942  8061 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/libsgmain_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@libsgmain_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:12:51.670  7693  7898 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/main/libsgsecuritybody_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@main@libsgsecuritybody_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:12:51.904  7693  7898 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/main/libsgavmp_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@main@libsgavmp_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:12:52.127  7693  7898 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/main/libsgsgmiddletier_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@main@libsgsgmiddletier_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:12:53.221  7693  7693 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:12:58.584  8439  8439 E HwOUC   : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:13:03.658  8623  8623 D HwIntelligent3_PropertiesUtil: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-26 13:13:03.658  8623  8623 D HwIntelligent3_PropertiesUtil: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
02-26 13:13:03.658  8623  8623 D HwIntelligent3_PropertiesUtil: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-26 13:13:03.658  8623  8623 D HwIntelligent3_PropertiesUtil: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:13:21.608  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-26 13:13:21.608  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
02-26 13:13:21.608  8689  8689 W System.err: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-26 13:13:21.608  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:13:21.619  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
02-26 13:13:21.619  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
02-26 13:13:21.619  8689  8689 W System.err: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-26 13:13:21.619  8689  8689 W System.err: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 13:13:25.497  8905  8905 D CrashReport-Native: Parsing line: eebe8000-eec40000 r--p 00000000 fe:00 89605                              /data/dalvik-cache/arm/system@framework@XposedBridge.jar@classes.dex
02-26 13:13:25.497  8905  8905 D CrashReport-Native: Parsing line: eec40000-eec89000 r-xp 00058000 fe:00 89605                              /data/dalvik-cache/arm/system@framework@XposedBridge.jar@classes.dex
02-26 13:13:25.497  8905  8905 D CrashReport-Native: Parsing line: eec89000-eec8a000 rw-p 000a1000 fe:00 89605                              /data/dalvik-cache/arm/system@framework@XposedBridge.jar@classes.dex
02-26 13:13:35.501  7942  8545 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/libsgsecuritybody_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@libsgsecuritybody_315417600000.zip@classes.dex) because non-0 exit status
02-26 13:13:51.827  7942  8081 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=cortex-a53 --instruction-set-features=default --dex-file=/data/user/0/com.huawei.hwvplayer.youku/app_SGLib/app_1582376631/libsgmisc_315417600000.zip --oat-file=/data/dalvik-cache/arm/data@user@0@com.huawei.hwvplayer.youku@app_SGLib@app_1582376631@libsgmisc_315417600000.zip@classes.dex) because non-0 exit status
```

**Comment by sdieedu** [comment]
今天可知APP可以阅读pdf书，我小米平板测试了，中兴手机c2017不可以阅读，怀疑手机系统原因。
 xposed+可知下载模块。 读书，显示可知下载抓获数据。模块里面可以看到可知app里面浏览的pdf书名，点击下载，未知错误，自动重启。再次打开可知下载，点击下载，消息一闪而过：从0开始下载，共xxx页。但是一直没有成功。
平板TF卡找不到下载目录，平板内部存储也无法找到下载的pdf。 虽然平板keledge-download 里面有截获的key等文件。
权限都全部设置好了。

**Comment by zzyandzzy** [comment]
> 今天可知APP可以阅读pdf书，我小米平板测试了，中兴手机c2017不可以阅读，怀疑手机系统原因。
> xposed+可知下载模块。 读书，显示可知下载抓获数据。模块里面可以看到可知app里面浏览的pdf书名，点击下载，未知错误，自动重启。再次打开可知下载，点击下载，消息一闪而过：从0开始下载，共xxx页。但是一直没有成功。
> 平板TF卡找不到下载目录，平板内部存储也无法找到下载的pdf。 虽然平板keledge-download 里面有截获的key等文件。
> 权限都全部设置好了。

获取了key的和url的json话那你直接可以用这个python脚本下载了。[README.md](https://github.com/zzyandzzy/xp_keledge/commit/7eee8482c00b0c81adab61b77cf71a10369239bb)

**Comment by sdieedu** [comment]
C:\Users\homepc\AppData\Local\Programs\Python\Python37>
python download.py -k rMXhkCHcBfksMJ&m -n 少博士趣学Python

usage: download.py [-h] [-k KEY] [-n NAME]

optional arguments:
  -h, --help            show this help message and exit
  -k KEY, --key KEY     input the key
  -n NAME, --name NAME  input books's name
'm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

pip 安装好了所有模块，key 也从580472604108787712.pdf 看到了 ，json文件改名放入 download.py同一目录下。运行 python download.py -k rMXhkCHcBfksMJ&m -n 少博士趣学Python
还是出现这个奇怪的错误
平板截获的key+json https://www.lanzous.com/i9p87hg

**Comment by zzyandzzy** [comment]
```
python download.py -k 'rMXhkCHcBfksMJ&m' -n '少博士趣学Python'
```
key里面包含特殊符号，用''包含

**Comment by sdieedu** [comment]
C:\Users\homepc\AppData\Local\Programs\Python\Python37>
python download.py -k 'rMXhkCHcBfksMJ&m' -n '少博士趣学Python'
非常感谢亲热心
usage: download.py [-h] [-k KEY] [-n NAME]

optional arguments:
  -h, --help            show this help message and exit
  -k KEY, --key KEY     input the key
  -n NAME, --name NAME  input books's name
'm'' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by zzyandzzy** [comment]
额，把下面的代码替换成
```python
parser = argparse.ArgumentParser()
parser.add_argument('-k', '--key', dest='key', help="input the key")
parser.add_argument('-n', '--name', dest='name', help="input books's name")
args = parser.parse_args()
 if args.key == None or args.name == None:
    parser.print_help()
    os._exit(0)
```
```python
key = r'rMXhkCHcBfksMJ&m'
name = '少博士趣学Python'
```
搜索args.key替换为key
搜索args.name替换为name

**Comment by sdieedu** [comment]
import os
import json
import argparse
import requests
import progressbar
from PyPDF2 import PdfFileMerger
key = r'rMXhkCHcBfksMJ&m'
name = '少博士趣学Python'


hex_ascii_key = ''
for i in key:
    hex_ascii_key += f'{ord(i):x}'
try:
    with open('res.json', 'r') as f:
        data = json.load(f)
except Exception as e:
    print(e)
bookurls = data['Data']['SplitFileUrls']
tmp_dir = 'download_%s' % name
tmp_index = 0
if not os.path.exists(tmp_dir):
    os.system(f'mkdir {tmp_dir}')
else:
    file_type = ".pdf"
    lst = []
    for root, dirs, files in os.walk(tmp_dir):
        for file in files:
            if file_type == '':
                lst.append(file)
            else:
                if os.path.splitext(file)[1] == str(file_type):
                    lst.append(file)
    tmp_index = lst.__len__()
    print("pass " + str(tmp_index) + " pages")
p = progressbar.ProgressBar()
for url in p(bookurls):
    page = bookurls.index(url) + 1
    if page > tmp_index:
        filename = f"x-{page}"
        r = requests.get(url=url, stream=True)
        with open(tmp_dir + '/' + filename + '.aes', 'wb') as f:
            f.write(r.content)
        os.system(
            f'openssl enc -d -aes-128-ecb -K {hex_ascii_key} -in {tmp_dir}/{filename}.aes -out {tmp_dir}/{filename}.pdf')
        os.system(f'rm {tmp_dir}/*.aes')
print("Synthesizing PDF file.........")
for root, dirs, files in os.walk(tmp_dir):
    if '.DS_Store' in files:
        files.remove('.DS_Store')
    files.sort(key=lambda x: int(x[x.rfind('-') + 1:][:-4]))
    file_list = [tmp_dir + '/' + file for file in files]
    merger = PdfFileMerger(strict=False)
    for pdf in file_list:
        merger.append(pdf)
    path = name + '.pdf'
    merger.write(path)
print("Success !!!!")
os.system(f'rm -rf {tmp_dir}')


=======================================
 修改替换执行完毕后
RESTART: C:/Users/homepc/AppData/Local/Programs/Python/Python37/download.py 
Traceback (most recent call last):
  File "C:/Users/homepc/AppData/Local/Programs/Python/Python37/download.py", line 19, in <module>
    bookurls = data['Data']['SplitFileUrls']
KeyError: 'Data'
=====================================
依然出错？

**Comment by zzyandzzy** [comment]
把
```python
bookurls = data['Data']['SplitFileUrls']
```
改成
```python
bookurls = data['SplitFileUrls']
```

**Comment by sdieedu** [comment]
感谢亲，可以下载，就是101页后都是1k小文件，被封杀IP了。删除小文件，再次跑代码 依然无法下载剩余部分
能否在下载一页后，加延迟函数，确保不太快被封杀

**Comment by zzyandzzy** [comment]
> 感谢亲，可以下载，就是101页后都是1k小文件，被封杀IP了。删除小文件，再次跑代码 依然无法下载剩余部分
> 能否在下载一页后，加延迟函数，确保不太快被封杀

每个ip 5分钟只能下载100页，这个脚本也是引用别人的，你只有下载100页的时候强制停止或者你自己修改下源码，把解码那部分直接抛出异常（目前是解码失败也保存为pdf）就行了，再加个检查完整性，这些我的可知下载都已经做了，我也不写python所以帮不了你了

**Comment by sdieedu** [comment]
非常感谢亲的回复和工作，有key就已经是完美了 ！
顺便问个问题：高教书苑和可知一样的阅读界面 https://ebook.hep.com.cn/ebooks/index.html#/
它的教材恰好是本学期在用的教材，能研究一下吗？

**Comment by sdieedu** [comment]
DeviceToken=931df2b8-22a8-63e5-8882-6532de5cb7df&ApiName=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&BridgePlatformName=kezhi_web&random=0.6479121451716638&nonce=1c287743-5fe9-4837-9983-208f2fa63c8c&AppId=29&timestamp=2020-02-27+02%3A37%3A19&apiversion=1.0&appversion=1.6.3&authorzieParameters=%7B%22contentexternalid%22%3A%22P00079-01-9787040471700-Pdf%22%2C%22organizationExternalId%22%3A%22%22%2C%22isOnline%22%3Atrue%2C%22device%22%3A%7B%22keyencrypttype%22%3A%22rsa%22%2C%22devicekey%22%3A%22-----BEGIN+PUBLIC+KEY-----%5CnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuCXUMbPL8XRXHb6hHHMR%5CnMlL1XMjY0MTQ2MjU1MTQ1MTYxMjQ2MjM1MjE5MTc3MjEzMTk4MTQ0MTYyMjA1MTYxMTI4MjEyMTgwMTYzMjIwMjQ5MTI5MTI4MjQyMTQ1MTQ0MTI5MTc2MjMxMjE5MTI4MTQ2MjAyMTYxMjMwMTI4MjIzMjE3MTk5MjAyMTI4MTQ1DJu5wUJxO93EWsSOrlikUoCSVdiRi9UKiBnKG%2FOX2%2Fd8ncbNaMft1%2FDL3Rv%5CnLOorYBkXydALkhsZnGrKB34XEm%2B755tdNjWAYMRFjJaDFtc%2B1AKjQlvIVGhMIRAr%5CnjIAVk1aPmhIGIMsBHCPv3sW2yxoFCCpzdyLTmOhNl1J1gzP6UbZmGipWlZZINsJ9%5CnNbObYmmuBmkKuOSs7Uhvtjv6FSFnUmct2mrcgXPbO8nyR9eazBvTTG4oJ1J9dhAn%5Cnns9fRxmMuxlRENKfULj8eTSP7QJoEYRPv5sDmfWuyTN1PKk8kAS8%2Bx1e8qQWvAJh%5CnjwIDAQAB%5Cn-----END+PUBLIC+KEY-----%22%2C%22DeviceType%22%3A4%2C%22Title%22%3A%22%E7%94%B5%E8%84%91%E8%AF%95%E8%AF%BB%22%7D%2C%22FromSalePlatformTitle%22%3A%22%E5%8F%AF%E7%9F%A5%22%2C%22userinfo%22%3A%7B%22nickname%22%3A%22%E6%9C%AA%E7%99%BB%E5%BD%95%22%2C%22ExternalId%22%3A%22%E6%9C%AA%E7%99%BB%E5%BD%95%22%7D%7D&Token=cd60bedf2ee2f7c0c261fe2be6fa3e40f1cfb2ee
高教书苑明显就是可知里面的书，不过，可知里面搜不到这本教材而已，能给个？

**Comment by zzyandzzy** [comment]
> DeviceToken=931df2b8-22a8-63e5-8882-6532de5cb7df&ApiName=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&BridgePlatformName=kezhi_web&random=0.6479121451716638&nonce=1c287743-5fe9-4837-9983-208f2fa63c8c&AppId=29&timestamp=2020-02-27+02%3A37%3A19&apiversion=1.0&appversion=1.6.3&authorzieParameters=%7B%22contentexternalid%22%3A%22P00079-01-9787040471700-Pdf%22%2C%22organizationExternalId%22%3A%22%22%2C%22isOnline%22%3Atrue%2C%22device%22%3A%7B%22keyencrypttype%22%3A%22rsa%22%2C%22devicekey%22%3A%22-----BEGIN+PUBLIC+KEY-----%5CnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuCXUMbPL8XRXHb6hHHMR%5CnMlL1XMjY0MTQ2MjU1MTQ1MTYxMjQ2MjM1MjE5MTc3MjEzMTk4MTQ0MTYyMjA1MTYxMTI4MjEyMTgwMTYzMjIwMjQ5MTI5MTI4MjQyMTQ1MTQ0MTI5MTc2MjMxMjE5MTI4MTQ2MjAyMTYxMjMwMTI4MjIzMjE3MTk5MjAyMTI4MTQ1DJu5wUJxO93EWsSOrlikUoCSVdiRi9UKiBnKG%2FOX2%2Fd8ncbNaMft1%2FDL3Rv%5CnLOorYBkXydALkhsZnGrKB34XEm%2B755tdNjWAYMRFjJaDFtc%2B1AKjQlvIVGhMIRAr%5CnjIAVk1aPmhIGIMsBHCPv3sW2yxoFCCpzdyLTmOhNl1J1gzP6UbZmGipWlZZINsJ9%5CnNbObYmmuBmkKuOSs7Uhvtjv6FSFnUmct2mrcgXPbO8nyR9eazBvTTG4oJ1J9dhAn%5Cnns9fRxmMuxlRENKfULj8eTSP7QJoEYRPv5sDmfWuyTN1PKk8kAS8%2Bx1e8qQWvAJh%5CnjwIDAQAB%5Cn-----END+PUBLIC+KEY-----%22%2C%22DeviceType%22%3A4%2C%22Title%22%3A%22%E7%94%B5%E8%84%91%E8%AF%95%E8%AF%BB%22%7D%2C%22FromSalePlatformTitle%22%3A%22%E5%8F%AF%E7%9F%A5%22%2C%22userinfo%22%3A%7B%22nickname%22%3A%22%E6%9C%AA%E7%99%BB%E5%BD%95%22%2C%22ExternalId%22%3A%22%E6%9C%AA%E7%99%BB%E5%BD%95%22%7D%7D&Token=cd60bedf2ee2f7c0c261fe2be6fa3e40f1cfb2ee
> 高教书苑明显就是可知里面的书，不过，可知里面搜不到这本教材而已，能给个？

我要下的书籍基本下到了，现在不搞了，你要想下载自己去破解，原理源代码都已经给了的。
