### ISSUE TITLE
APP未知错误，网页端正常

### ISSUE THREAD

**Issue by sdieedu** [zzyandzzy/xp_keledge#3]
多版本可知app，测试了一下：点击pdf书籍后，提示### 发生异常错误，请稍候再试！2秒后退出阅读
问题是：网页阅读无障碍啊
咋办？

**Comment by zzyandzzy** [comment]
可知版本多少？
可否贴上log？
激活Xposed模块，手机USB链接电脑，输入
```
adb logcat | grep "Xposed"
```
打开可知点击阅读，并贴上完整log

**Comment by sdieedu** [comment]
算了 我放弃吧 
我用的太极，没root，问太极作者要的无极码，开启超级模式。也可以勾选亲的模块
手机是zte 。我用可知最新版，也用过稍低版本
可知app无论那个版本，登录没问题，就是查看书，总是显示发生异常错误，请稍候再试！2秒后退出阅读
问题是：网页阅读无障碍啊
谢谢亲的软件 
可能我手机问题，反正可知很快就没法免费阅读了 呵呵

**Comment by zzyandzzy** [comment]
太极阴没测试过，我用的太极阳模式。
