### ISSUE TITLE
可否改解密方式改为截屏方式

### ISSUE THREAD

**Issue by sdieedu** [zzyandzzy/xp_keledge#4]
今天换平板测试：小米平板安装官网提供的app，pdf所有的书籍只有第一页可以观看，其他翻页出不来，epub翻页迅速清晰。
可否改成自动翻页截屏方式？简单高效不违法

**Comment by sdieedu** [comment]
坐标山东联通

**Comment by zzyandzzy** [comment]
技术上来说可以实现，现在可知下载已经实现截取密匙-下载-合并pdf一体化功能了，而且免费也只有几天了，就没必要搞了
